### ISSUE TITLE
uninitialized constant Lurker::Spy::Forwardable

### ISSUE THREAD

**Issue by edwardloveall** [razum2um/lurker#94]
When I add

```ruby
require 'lurker/spec_helper'
```
to my `spec_helper`, I get the following error when running rspec:

```
/Users/user/.gem/ruby/2.2.0/gems/lurker-0.6.0/lib/lurker/spy.rb:10:in `<class:Spy>': uninitialized constant Lurker::Spy::Forwardable (NameError)
	from /Users/user/.gem/ruby/2.2.0/gems/lurker-0.6.0/lib/lurker/spy.rb:4:in `<module:Lurker>'
	from /Users/user/.gem/ruby/2.2.0/gems/lurker-0.6.0/lib/lurker/spy.rb:3:in `<top (required)>'
	from /Users/user/.rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/user/.rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/user/.gem/ruby/2.2.0/gems/lurker-0.6.0/lib/lurker/spec_helper/rails.rb:1:in `<top (required)>'
	from /Users/user/.rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/user/.rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/user/.gem/ruby/2.2.0/gems/lurker-0.6.0/lib/lurker/spec_helper.rb:1:in `<top (required)>'
	from /Users/user/.rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /Users/user/.rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /Users/user/.rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Users/user/Code/rails/humon/spec/spec_helper.rb:2:in `<top (required)>'
	from /Users/user/.rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/user/.rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/user/.gem/ruby/2.2.0/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1025:in `block in requires='
	from /Users/user/.gem/ruby/2.2.0/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1025:in `each'
	from /Users/user/.gem/ruby/2.2.0/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1025:in `requires='
	from /Users/user/.gem/ruby/2.2.0/gems/rspec-core-3.0.4/lib/rspec/core/configuration_options.rb:101:in `block in process_options_into'
	from /Users/user/.gem/ruby/2.2.0/gems/rspec-core-3.0.4/lib/rspec/core/configuration_options.rb:100:in `each'
	from /Users/user/.gem/ruby/2.2.0/gems/rspec-core-3.0.4/lib/rspec/core/configuration_options.rb:100:in `process_options_into'
	from /Users/user/.gem/ruby/2.2.0/gems/rspec-core-3.0.4/lib/rspec/core/configuration_options.rb:22:in `configure'
	from /Users/user/.gem/ruby/2.2.0/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:96:in `setup'
	from /Users/user/.gem/ruby/2.2.0/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:85:in `run'
	from /Users/user/.gem/ruby/2.2.0/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:70:in `run'
	from /Users/user/.gem/ruby/2.2.0/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:38:in `invoke'
	from /Users/user/.gem/ruby/2.2.0/gems/rspec-core-3.0.4/exe/rspec:4:in `<top (required)>'
	from /Users/user/.gem/ruby/2.2.0/bin/rspec:23:in `load'
	from /Users/user/.gem/ruby/2.2.0/bin/rspec:23:in `<main>'
```

I'm running Rails 4.2.0 and Ruby 2.2.0p0

**Comment by razum2um** [comment]
hi @edwardloveall I haven't tested it with 4.2 since I saw 4.2.0.beta2 which didn't work out of the box (for some other reason, I don't remember now)

will see into the issue a pair days later

btw. you're using 0.6.0 but the actual version is 0.6.6 and should be able easy to update.

**Comment by edwardloveall** [comment]
Cool. Tried 0.6.6 and got a different error documented in #95. This can be closed if you want unless you're planning on supporting 0.6.0.

**Comment by Strech** [comment]
@edwardloveall Sorry, but `v0.6.0` is not supported now. I'll try help you in #95
